version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: video-transcoder:latest
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ~/.aws:/root/.aws:ro